{
 "title": "API - Database monitoring",
 "tags": [
  "nodejs",
  "express",
  "api",
  "monitoring",
  "database"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Percentuale di Utilizzo CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (rate(process_cpu_user_seconds_total[1m]) + rate(process_cpu_system_seconds_total[1m]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Utilizzo Memoria RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Memory Usage" }
   ]
  },
  {
   "title": "Conteggio Totale Richieste API per Percorso",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(api_calls_total) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Durata Richieste HTTP per Percorso (95° percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_milliseconds_bucket[5m])) by (le, route)) * 1000",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Conteggio Codici HTTP di Risposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_request_duration_milliseconds_count) by (code)",
     "legendFormat": "HTTP {{code}}"
    }
   ]
  },
  {
   "title": "Conteggio Query Database per Tipo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(db_query_duration_seconds_count) by (query_type)",
     "legendFormat": "{{query_type}}"
    }
   ]
  },
  {
   "title": "Durata Query Database per Tipo (95° percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_query_duration_seconds_bucket[5m])) by (le, query_type))",
     "legendFormat": "{{query_type}}"
    }
   ]
  }
 ]
}